### ISSUE TITLE
iOS 9.2.1

### ISSUE THREAD

**Issue by ahsolanki** [abbyysdk/ocrsdk.com#41]
I'm using OCRSDK for iOS but for iOS Version 9.2.1, it is crashing and even in the given demo, it is crashing. anyone have faced issue ?
Please help me to resolve this issue.

**Comment by Dmitry-Me** [comment]
Do you have any more details? Perhaps a call stack and steps to reproduce?

**Comment by idevu** [comment]
Hi all. I have same problem as ahsolanki. 
I downloaded a sample project from your website and here. Both examples crashed with the following message:"App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure. Temporary exceptions can be configured via your app's Info.plist file." 

When comment code with setting installationID in RecognitionVC -> viewDidAppear.
I catch previous message + 
![screen shot 2016-03-16 at 13 16 52](https://cloud.githubusercontent.com/assets/17871836/13804667/bd312d6e-eb70-11e5-8bca-4392269c8cec.png) but app not crashing.

I set Deployment Target: iOS 9.0
I using Xcode 7.2.1 version.
 
You use deprecated methods (since iOS 9.0) in 
1.HTTPOperation.m for start connection:
NSURLConnection initWithRequest:(NSURLRequest *)request delegate:(nullable id)delegate startImmediately:(BOOL)startImmediately NS_DEPRECATED(10_5, 10_11, 2_0, 9_0,");

2.Client.m getting activationInfo:
NSURLSession NSURLsendSynchronousRequest:(NSURLRequest *)request returningResponse:(NSURLResponse * __nullable * __nullable)response error:(NSError **)error NS_DEPRECATED(10_3, 10_11, 2_0, 9_0,");

When i send GET request (http://cloud.ocrsdk.com/activateNewInstallation?deviceId=<My real device ID>) with valid password and appName (other request is working!)
I catch empty authToken:
"
![screen shot 2016-03-16 at 13 38 26](https://cloud.githubusercontent.com/assets/17871836/13805385/1ef16442-eb76-11e5-9be6-e5bbbdeba7f5.png)
"
To request I use Postman app.
To use your SDK should get installationID for device?

**Comment by Dmitry-Me** [comment]
@idevu Is the problem arising because the URIs being requested start with `http://`?

**Comment by idevu** [comment]
I test https request and catch same response: 
![screen shot 2016-03-16 at 15 10 40](https://cloud.githubusercontent.com/assets/17871836/13807030/e326424c-eb80-11e5-9363-d77188947ba3.png)

**Comment by idevu** [comment]
Ok. I change request protocol in Client implementation and request completed and i catch valid result!

But you can't wrote about insatllationID. Should I use it in my app?

**Comment by Dmitry-Me** [comment]
@idevu *installationId* is a deprecated concept which shouldn't be used by new applications. Samples are to be updated such that they only use the *applicationId* when authenticating with the service.

**Comment by idevu** [comment]
Ok. I see. Thanks for the info.

**Comment by Dmitry-Me** [comment]
https://github.com/abbyysdk/ocrsdk.com/commit/093519ecf98b62dff72147cba9d9e1d44cdfa3c4 should resolve this
